# -*- coding: utf-8 -*-
"""HelloWorld.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YxTRrvYL_ujU4aBrd1bAzu9DmbJxLers
"""

name = "apple"
for letter in name:
  print(letter)

print("Hello World")

for i in range(5):
  print("I")
  print("ate")
  print("food")