# -*- coding: utf-8 -*-
"""python_workshop

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RYSXAWMJ8nub50_djg_gVAXVYtVQJvq0
"""

course_title = "Python Workshop-Part1"
speaker1 = "Evelyn and Stuti"
print("This course title is Python Workshop-Part1 hosted by", speaker1)
print(f"This course title is {course_title} hosted by {speaker1}")

emails = ['a@gmail.com', 'b@work.com', 'c@gmail.com', 'd@school.edu']
x = list(filter(lambda e: 'gmail.com' not in e, emails))
print(x)

student = {
  "name": "Emma",
  "class": 9,
  "marks": 75
}
m = student.get("marks")
print(m)

x = input("Enter a number: ")
if x != 2:
  print("x is not = 0")

def avg_PM25(state):

    # get the lines from the file
    inFile = open("uspoll.txt","r")
    lines = inFile.readlines()
    inFile.close()

    # calculate the average
    total = 0
    count = 0
    for line in lines:
        values = line.split(":")
        curr25 = float(values[2])
        cityState = values[1]
        values = cityState.split(",")
        curr_state = values[0]
        if curr_state.find(state) > 0:
            total += curr25
            count += 1
            return total / count

print(avg_PM25('OH'))

x = 20
y = 4
print(x+y)
print(x-y)
print(x%y)
print(x//y)
print(x**y)

counter = 1
sum = 0
while counter <= 6:
    sum = sum + counter
    counter = counter + 2
print(sum)

def mystery(nums):
    total = 0
    for num in nums:
        if num == 999:
            break
        else:
            total += num
    return total

mystery([8, 2, 999, 5, 4])

# @title chapter 6
def countdown():
    counter = 10
    answer = " "
    while counter > 0:
       answer += str(counter) + " "
       counter = counter - 1
    return answer
countdown()

fruit = "fruit"
index = 0
while index < len(fruit):
  letter = fruit[index]
  print(letter)
  index = index + 1

sum = 0
for i in range(1,5):
  sum = sum + i
  print(sum)

camels = 42
print('In %d years I have spotted %g %s.' % (3, 0.1, 'camels'))

output = ""
var1 = -2
var2 = 0
while var1 != 0:
    var1 = var1 + 1
    var2 = var2 - 1
print("var1: " + str(var1) + " var2 " + str(var2))

i = 0
sum = 0
a = [3, 8, 2, -1, 10]
while i < len(a) and a[i] > 0:
    sum += a[i]
    i += 1
print(sum)

weight = 120
height = 160

BMI = (weight/height**2)
print(BMI)

#set variables to a number
savings = 100
monthly_savings = 10
num_months = 4

new_savings = 500
print("new_savings: ", new_savings)

total_savings = savings + new_savings

print("The total_savings are:", str(total_savings))

#if/else statements
a = 90
b = 90
if b > a:
  print("b is greater than a")
elif a > b:
  print("b is less than a")
else:
  print("they are equal")

d = 0
e = 10
if d < e:
  d = d + 1
if d%2!=0:
  print(d)

credit_score = int(input("credit score: "))
if credit_score >= 5000:
  print("yes")
  if credit_score <= 5000:
    print("you could still qualify")
    if credit_score <= 2000:
      print("you might not qualify")
    else:
      print("you qualify")
else:
  print("you do not qualify")

day1 = ["Megan", "Felix", "Jameil", "Mary"]
print(day1)
#print("day1 = ", day1)
print(day1[-3], day1[-3])

#practicing list functions
my_list = ["samoyed", "polar bear", "sloth", "beluga"]
your_list = ["turtle", "husky", "golden retriever", "penguin"]
print("my_list =", your_list + my_list)

your_list.append("orange cat")
your_list

your_list.insert(2, "peach")
your_list

''' introduction to lists '''

#sorts the list in alphabetical order
my_list.sort()
my_list

string = "X-DSPAM-Confidence: 0.8475"
file = string.find('0.8475')
string = string[20:26]
num = float(string)
print(num)

def phrase(person, thing):
    person = person.capitalize()
    thing = thing.lower()
    return str(person) + " " + str(thing)

print(phrase("Shiqi","Likes to code"))

def item_purchase(item, price):
    return "My" + " " + item + " " + "cost" + " " + "$" + str(price)
print(item_purchase("makeup", 14))

def item_purchase(item, price):
    return f"My {item} cost ${price:.2f}"

print(item_purchase("makeup", 14))

while True:
    line = input('Word: ')
    if line == 'done':
        break
    print(line)
print ('Done!')

s = "hello"
print(s[-4:])

total = 0
for i in range(1, 6):
  total += i
print("The total is: ", total)

numbers = [15, 22, 8, 19, 00000000]

for x in range(1, 4):
    for y in range(1, 11):
        print(str(x), " * ", str(y), " = ", x * y)
        y = y + 1