# -*- coding: utf-8 -*-
"""WhatAboutPrint_02-02-26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ayN7UHROYtzDV3GsiGlmWYSXbeuv3V1u
"""

print("Hello World")

dir(print) #dir = shorthand for directory

x = "Hello World!"

print(x.upper())
#print(x.lower())

print = x

print("Hello World!")

dir(x)

def f2c(f_temp):
  """ Convert a temperature from Fahrenheit to Celsius """
  c_temp = (f_temp - 32) * 5 / 9
  return c_temp

print(str(int(f2c(14))) + " degrees Celsius")

smallest_so_far = -1
for the_num in [9, 41, 12, 3, 74, 15] :
   if the_num < smallest_so_far :
      smallest_so_far = the_num
print(smallest_so_far)

tot = 0
for i in [5, 4, 3, 2, 1] :
    tot = tot + 1
print(tot)

n = 0
while n > 0 :
    print('Lather')
    print('Rinse')
print('Dry off!')

str1 = "Hello"
str2 = 'there'
bob = str1 + str2
print(bob)

fruit = 'Banana'
fruit = 'b' + fruit[1:] # Create a new string with the desired change
print(fruit)

stuff = dict()
print(stuff.get('candy',-1))

tmp = list()
for k, v in c.items() :
    tmp.append( (v, k) )

x , y = 3, 4

x = { 'chuck' : 1 , 'fred' : 42, 'jan': 100}
y = x.items()